# Default values for dataset-raw-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}
appParams:
  competingConsumers: 2
  computeBucketBoundariesUsingPresto: false
  eventQueueHandlerMonitorIntervalInSec: 2
  maxBufferedEvents: 60000
  numBacktrackDaysToDetect: 5
  numORCInSegment: 4
  orcInventoryBatchFetchSize: 20000
  segmentSizeBufferPCNT: 15
  segmentSizeGB: 1.0
autoscaling:
  enabled: true
  eventQueueHandlerOccupancyPercentage: 80
  maxReplicas: 5
  minReplicas: 1
  scaleDownPeriod: 60
  scaleUpPeriod: 30
containerResources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 512Mi
db:
  max_idle_connections: 1
  max_open_connections: 3
fullnameOverride: ""
image:
  repository: snappyflowml/dataset-raw-controller
  pullPolicy: IfNotPresent
  tag: 'master-2-0-86'
nameOverride: ""
nodeSelector: {}
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "9000"
  prometheus.io/scrape: "true"
podSecurityContext: {}
replicaCount: 1
schedules:
  detect_raw_time_buckets: '0 * * * *'
  process_raw_data: '0 1 * * *'
  raw_version_compacted: '0 5 * * *'
securityContext: {}
serverPort: :5002
service:
  servicePort: 5002
tolerations: []
