enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  {}

sfapmui:
  image:
    repository: snappyflowml/sfapm-ui
    tag: '3.1.450'
    pullPolicy: IfNotPresent

