enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: ""

podSecurityContext:
  {}

sfapmui:
  image:
    brand: ""
    repository: snappyflowml/sfapm-ui
    tag: 'master-3-1-474'
    tag_esds: 'master-3-1-454esds'
    tag_goals101: ''
    tag_visa: ''
    pullPolicy: IfNotPresent

