enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: ""

podSecurityContext:
  {}

sfapmui:
  image:
    repository: snappyflowml/sfapm-ui
    tag: '3-1-462'
    tag_esds: '3-1-462esds'
    tag_goals101: ''
    tag_visa: ''
    pullPolicy: IfNotPresent

