---
enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""
pprof:
  image:
    repository: snappyflowml/pprof-server
    pullPolicy: IfNotPresent
    tag: 'master-0-4-1'
podSecurityContext: {}