affinity: {}
containerResources:
  signatures:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/signatures
  tag: '11'
nameOverride: ''
nodeSelector: {}
service:
  servicePort: 8888
tolerations: []
useDefaultPatterns: false
