affinity: {}
compactionImage: snappyflowml/spark-compact-orc:4
fullnameOverride: ''
jobserver:
  containerResources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 50Mi
  image:
    pullPolicy: Always
    repository: snappyflowml/job-server
    tag: 'dev-test'
  serverPort: 5002
  service:
    servicePort: 5002
  sparkProperties:
    logDirectory: sparkhs/spark-hs
monitor:
  containerResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi
  image:
    pullPolicy: Always
    repository: snappyflowml/monitor
    tag: 'dev-test'
nameOverride: ''
nodeSelector: {}
tolerations: []
