apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-apm
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: server
data:
    DISABLE_SERVER_SIDE_CURSORS: {{ .Values.disable_server_side_cursors | quote }}

    {{- if .Values.postgresql.enabled }}
    DB_HOST: {{ .Release.Name }}-postgresql
    DB_PORT: "5432"
    DB_NAME: "snappyflow"
    DB_USER: {{ .Values.postgresql.multidbUser }}
    {{- else }}
    DB_HOST: {{ .Values.postgresql.external.dbHost }}
    DB_PORT: {{ .Values.postgresql.external.dbPort | default "5432"  | quote }}
    DB_NAME: "snappyflow"
    DB_USER: {{ .Values.postgresql.external.dbUser }}
    DB_PASSWORD: {{ .Values.postgresql.external.dbPassword }}
    {{- end }}

    REDIS_HOST: {{ .Release.Name  }}-redis
    REDIS_PORT: "6379"

    ARCHIVER_ENABLED: {{ .Values.archiverEnabled }}

    VIZBUILDER_HOST: {{ include "sfapm.fullname" . }}-vizbuilder
    VIZBUILDER_PORT: "{{ .Values.vizbuilder.service.port }}"

    COMMANDSERVER_HOST: {{ include "sfapm.fullname" . }}-commands
    COMMANDSERVER_PORT: "{{ .Values.commands.service.port }}"

    ES_MANAGER_HOST: {{ include "sfapm.fullname" . }}-esmanager
    ES_MANAGER_PORT: "{{ .Values.esmanager.service.port }}"

    SERVERID: "{{ .Values.sfapm.serverid }}"

    {{- if .Values.keycloak.enabled }}
    KEYCLOAK_MODE: "True"
    KEYCLOAK_SERVER: "{{ .Values.keycloak.serverIP }}"
    KEYCLOAK_USER: "{{ .Values.keycloak.user }}"
    KEYCLOAK_PASSWORD: "{{ .Values.keycloak.password }}"
    KEYCLOAK_REALM: "{{ .Values.keycloak.realm }}"
    KEYCLOAK_CLIENTID: "{{ .Values.keycloak.clientid }}"
    KEYCLOAK_CLIENTKEY: "{{ .Values.keycloak.clientkey }}"
    KEYCLOAK_PUBLICKEY: "{{ .Values.keycloak.publickey }}"
    SUPPORT_EMAIL: "{{ .Values.keycloak.supportemail }}"
    WEBSITE_URL: "{{ .Values.keycloak.websiteurl }}"
    DEFAULT_PROFILE: "{{ .Values.keycloak.defaultprofile }}"
    {{- else }}
    KEYCLOAK_MODE: ""
    {{- end }}
    {{- if .Values.sfapm.rollover.custom_config }}
    METRIC_ROLLOVER_MAX_AGE: "{{ .Values.sfapm.rollover.metric.rollover_max_age }}"
    METRIC_ROLLOVER_MAX_DOCS: "{{ .Values.sfapm.rollover.metric.rollover_max_docs }}"
    METRIC_ROLLOVER_MAX_SIZE: "{{ .Values.sfapm.rollover.metric.rollover_max_size }}"
    LOG_ROLLOVER_MAX_AGE: "{{ .Values.sfapm.rollover.log.rollover_max_age }}"
    LOG_ROLLOVER_MAX_DOCS: "{{ .Values.sfapm.rollover.log.rollover_max_docs }}"
    LOG_ROLLOVER_MAX_SIZE: "{{ .Values.sfapm.rollover.log.rollover_max_size }}"
    TRACE_ROLLOVER_MAX_AGE: "{{ .Values.sfapm.rollover.trace.rollover_max_age }}"
    TRACE_ROLLOVER_MAX_DOCS: "{{ .Values.sfapm.rollover.trace.rollover_max_docs }}"
    TRACE_ROLLOVER_MAX_SIZE: "{{ .Values.sfapm.rollover.trace.rollover_max_size }}"
    PROFILE_ROLLOVER_MAX_AGE: "{{ .Values.sfapm.rollover.profile.rollover_max_age }}"
    PROFILE_ROLLOVER_MAX_DOCS: "{{ .Values.sfapm.rollover.profile.rollover_max_docs }}"
    PROFILE_ROLLOVER_MAX_SIZE: "{{ .Values.sfapm.rollover.profile.rollover_max_size }}"
    RUM_ROLLOVER_MAX_AGE: "{{ .Values.sfapm.rollover.rum.rollover_max_age }}"
    RUM_ROLLOVER_MAX_DOCS: "{{ .Values.sfapm.rollover.rum.rollover_max_docs }}"
    RUM_ROLLOVER_MAX_SIZE: "{{ .Values.sfapm.rollover.rum.rollover_max_size }}"
    CONTROL_ROLLOVER_MAX_AGE: "{{ .Values.sfapm.rollover.control.rollover_max_age }}"
    CONTROL_ROLLOVER_MAX_DOCS: "{{ .Values.sfapm.rollover.control.rollover_max_docs }}"
    CONTROL_ROLLOVER_MAX_SIZE: "{{ .Values.sfapm.rollover.control.rollover_max_size }}"
    {{- end }}

    SWITCH_OFF_PRESTO_COORD: "{{ .Values.sfapm.switchOffPrestoCoord }}"

    ARCHIVER_API_URL: "{{ .Values.sfapm.ingress.kafka_api }}"
    ARCHIVER_URL: "{{ .Values.sfapm.ingress.arhiver_url }}"

    KAFKA_USERNAME: "{{ .Values.sfapm.ingress.kafka_user }}"
    KAFKA_PASSWORD: "{{ .Values.sfapm.ingress.kafka_pwd }}"

    GOOGLE_CLIENT_ID: "{{ .Values.google_client_id }}"
    GOOGLE_CLIENT_SECRET: "{{ .Values.google_client_secret }}"
    GOOGLE_CALLBACK_URL_RELATIVE: "{{ .Values.google_callback_url }}"

    {{- if .Values.usage_system.enabled }}
    USAGE_SERVICE_HOST: "{{ .Values.usage_system.host }}"
    USAGE_SERVICE_PORT: "{{ .Values.usage_system.port }}"
    USAGE_SERVICE_TLS: "{{ .Values.usage_system.tls }}"
    {{- end }}

    {{- if .Values.ingest_usage_system.enabled }}
    USAGE_SYSTEM_HOST: "{{ .Values.ingest_usage_system.host }}"
    USAGE_SYSTEM_PORT: "{{ .Values.ingest_usage_system.port }}"
    {{- end }}

    PPROF_SERVER_HOST: "{{ include "sfapm.fullname" . }}-pprof-server"
    PPROF_SERVER_PORT: "{{ .Values.pprof.service.port }}"

    {{- if .Values.cloud.aws.enable }}
    CLOUD_TYPE: "aws"
    {{- else if .Values.cloud.gcs.enable }}
    CLOUD_TYPE: "gcp"
    GCP_SERVICE_ACCOUNT: "{{ .Values.cloud.gcs.service_account }}"
    GCP_REGION: "{{ .Values.cloud.gcs.region }}"
    GCP_ZONE: "{{ .Values.cloud.gcs.zone }}"
    {{- end }}
    {{- if .Values.sfapm.quotasEnabled }}
    QUOTAS_ENABLED: "True"
    {{- else }}
    QUOTAS_ENABLED: ""
    {{- end }}
