{{- if .Values.sfapm_celery.periodic.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sfapm.fullname" . }}-apm-celery-periodic
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sfapm.fullname" . }}-apm-celery-periodic
  minReplicas: {{ .Values.sfapm_celery.periodic.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sfapm_celery.periodic.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.sfapm_celery.periodic.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sfapm_celery.periodic.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.sfapm_celery.periodic.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.sfapm_celery.periodic.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
