apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-ui-sfagent
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: ui
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    metrics:
      plugins:
      - name: kube-sfagent-nginx
        enabled: true
        interval: 300
        config:
          location: status
          {{- if .Values.sfapmui.tls.enabled }}
          port: 443
          secure: true
          {{- else }}
          port: 80
          secure: false
          {{- end }}
    logging:
      plugins:
      - name: nginx-access
        enabled: true
        config:
          log_path: "/var/log/nginx/access.log"
          geo_info: {{ .Values.global.nginx_geo_info_collection}}
          ua_parser: {{ .Values.global.nginx_ua_parsing}}
          url_normalizer: true
      - name: nginx-error
        enabled: true
        config:
          log_path: "/var/log/nginx/error.log"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-sfagent-normalization-nginx
data:
  config.yaml: |+
    ---
    interval: 600
    dynamic_rule_generation:
      enabled: false #Rely on normalization algorithm for rule generation.
      rules_length_limit: 10000 #set the value to -1  for specifying no limit
      log_volume: 100000 #set the value to -1  for specifying no limit
    rules:
    - /admin/*
    - /admin/*/generatepassword
    - /snappyflow/accounts/*
    - /snappyflow/accounts/*/cache
    - /snappyflow/accounts/*/inventory
    - /snappyflow/accounts/*/permission
    - /snappyflow/accounts/*/templates
    - /snappyflow/applications/*
    - /snappyflow/applications/*/cloudtemplates/*
    - /snappyflow/applications/*/endpoints
    - /snappyflow/applications/*/endpoints/*
    - /snappyflow/applications/*/endpoints/*/agents
    - /snappyflow/applications/*/endpoints/*/agents/*
    - /snappyflow/applications/*/endpoints/*/agents/*/start
    - /snappyflow/applications/*/endpoints/*/agents/*/stop
    - /snappyflow/applications/*/endpoints/*/loggers
    - /snappyflow/applications/*/endpoints/*/monitoring
    - /snappyflow/applications/*/endpoints/*/monitoring/start
    - /snappyflow/applications/*/endpoints/*/monitoring/stop
    - /snappyflow/applications/*/endpoints/*/pluginmappings
    - /snappyflow/applications/*/endpoints/*/plugins
    - /snappyflow/applications/*/endpoints/*/plugins/*
    - /snappyflow/applications/*/endpoints/*/pollers
    - /snappyflow/applications/*/endpoints/*/pollers/*
    - /snappyflow/applications/*/endpoints/*/pollers/*/start
    - /snappyflow/applications/*/endpoints/*/pollers/*/stop
    - /snappyflow/applications/*/endpoints/*/tags
    - /snappyflow/applications/*/endpoints/endpoints/tasks/discoverServices
    - /snappyflow/applications/*/plugins
    - /snappyflow/applications/*/provision
    - /snappyflow/applications/*/provisionlog
    - /snappyflow/applications/*/services
    - /snappyflow/applications/app_property
    - /snappyflow/applications_alerts/*
    - /snappyflow/cloudprofiles/*
    - /snappyflow/cloudprofiles/*/credentials
    - /snappyflow/cloudprofiles/*/credentials/*
    - /snappyflow/cloudprofiles/*/ekey
    - /snappyflow/cloudprofiles/*/inventory
    - /snappyflow/cloudprofiles/*/keyfile
    - /snappyflow/cloudprofiles/*/ldap
    - /snappyflow/cloudprofiles/*/ldap/*
    - /snappyflow/cloudprofiles/*/notification/
    - /snappyflow/cloudprofiles/*/notification/*
    - /snappyflow/cloudprofiles/*/provision
    - /snappyflow/cloudprofiles/*/sso
    - /snappyflow/cloudprofiles/*/sso/*
    - /snappyflow/cloudtemplates/*
    - /snappyflow/clusters/*
    - /snappyflow/clusters/*/apps
    - /snappyflow/clusters/*/apps/*
    - /snappyflow/clusters/*/apps/*/monitoring
    - /snappyflow/clusters/*/apps/*/tags
    - /snappyflow/dashboard/*
    - /snappyflow/dashboard/*/componentapi
    - /snappyflow/dashboard/*/componentapi/*
    - /snappyflow/dashboardcomponent/*/permission
    - /snappyflow/dashboardcomponent/*/verify
    - /snappyflow/datasources/*
    - /snappyflow/datasources/*/cleanup
    - /snappyflow/datasources/*/doc_delete
    - /snappyflow/datasources/*/mapping
    - /snappyflow/datasources/*/rollover
    - /snappyflow/datasources/*/status
    - /snappyflow/escluster/*
    - /snappyflow/goprofile/*
    - /snappyflow/logarchival/config/presto
    - /snappyflow/logarchival/dataset
    - /snappyflow/logarchival/project
    - /snappyflow/logarchival/register
    - /snappyflow/logarchival/status/presto
    - /snappyflow/notification/teamverify
    - /snappyflow/notification/webhookverify
    - /snappyflow/plugins/*
    - /snappyflow/plugins/*/mapping
    - /snappyflow/plugins/*/mapping
    - /snappyflow/projects
    - /snappyflow/projects/*
    - /snappyflow/projects/*/applications
    - /snappyflow/projects/*/applications
    - /snappyflow/projects/*/applications/*
    - /snappyflow/projects/*/applications/*
    - /snappyflow/projects/*/applications/*/endpoints
    - /snappyflow/projects/*/applications/*/endpoints/*
    - /snappyflow/projects/*/appsdiscovery
    - /snappyflow/projects/*/autodiscoveryrule
    - /snappyflow/projects/*/dashboard/*/permission
    - /snappyflow/projects/*/inventory
    - /snappyflow/projects/*/permission
    - /snappyflow/projects/*/reconfigure
    - /snappyflow/projects/*/reconfigure/save
    - /snappyflow/projects/*/retention
    - /snappyflow/projects/*/tagsdiscovery
    - /snappyflow/projecttemplates/*
    - /snappyflow/secretkeys/*
    - /snappyflow/templaterepositories/*
    - /snappyflow/ziplog/*
    - /user/forgotpassword/check/*/*
    - /user/forgotpassword/confirm/*/*
    - /user/login/*/*
    - /vizbuilder/alert/app/*
    - /vizbuilder/alert/app/*/datasource
    - /vizbuilder/alert/download/template/*/id/*
    - /vizbuilder/alert/getAlerts/*
    - /vizbuilder/alert/getApplicationAlerts/*
    - /vizbuilder/alert/getApplicationAlerts/*
    - /vizbuilder/alert/getGroups/*
    - /vizbuilder/alert/getSavedAlerts/id/*
    - /vizbuilder/alert/getTemplate/*/*
    - /vizbuilder/alert/getTemplate/*/main
    - /vizbuilder/alert/template/upload/*/id/*
    - /vizbuilder/alert/templates/delete/id/*
    - /vizbuilder/logoperation/extraction/app/*
    - /vizbuilder/logoperation/extraction/infra/*
    - /vizbuilder/logoperation/extraction/template/*/*
    - /vizbuilder/querybuilder/committemplates/*
    - /vizbuilder/querybuilder/dashboard/*
    - /vizbuilder/querybuilder/dashboard/*/*
    - /vizbuilder/querybuilder/dashboard/components/*
    - /vizbuilder/querybuilder/dashboard/components/*/*
    - /vizbuilder/querybuilder/download/template/*/id/*
    - /vizbuilder/querybuilder/plugins/mappings/*/*
    - /vizbuilder/querybuilder/query/execute
    - /vizbuilder/querybuilder/repositories/*
    - /vizbuilder/querybuilder/repositories/*/*
    - /vizbuilder/querybuilder/template/*/type
    - /vizbuilder/querybuilder/template/*/type
    - /vizbuilder/querybuilder/template/upload/*/id/*
    - /vizbuilder/querybuilder/template/upload/*/id/*
    - /vizbuilder/querybuilder/templates/*
    - /vizbuilder/querybuilder/templates/*/type
    - /vizbuilder/querybuilder/templates/delete/id/*
    - /vizbuilder/querybuilder/templates/type/*/plugin/*/id/*
    - /vizbuilder/querybuilder/visualizations/*/*/components/content/*
    - /vizbuilder/querybuilder/visualizations/*/*/components/listComponents
    - /vizbuilder/querybuilder/visualizations/*/*/components/update/*
    - /vizbuilder/querybuilder/visualizations/*/*/group/*/tab/*/delete
    - /vizbuilder/querybuilder/visualizations/*/*/pane/clone
    - /vizbuilder/querybuilder/visualizations/*/*/tab/*/group/*/pane/*/delete
    - /vizbuilder/querybuilder/visualizations/*/*/tab/clone
    - /vizbuilder/querybuilder/visualizations/*/*/validate/importPane
    - /vizbuilder/querybuilder/visualizations/templates/templates/*/components/content/main
    - /vizbuilder/signature/operations/*