apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfapm.fullname" . }}-pprof-server
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: pprof
    role: pprof-server
    snappyflow/component: snappyflow-apm
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  replicas: {{ .Values.pprof.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfapm.selectorLabels" . | nindent 6 }}
      app: pprof
      role: pprof-server
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sfapm.selectorLabels" . | nindent 8 }}
        app: pprof
        role: pprof-server
        snappyflow/component: snappyflow-apm
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sfapm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: pprof-server
        image: "{{ .Values.pprof.image.repository }}:{{ .Values.pprof.image.tag }}"
        imagePullPolicy: {{ .Values.pprof.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8090
            protocol: TCP
        livenessProbe:
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: http
        readinessProbe:
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: http
        resources:
          {{- toYaml .Values.pprof.resources | nindent 12 }}
