{{- if .Values.sfapm.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sfapm.fullname" . }}-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: snappyflow-apm
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-ui
            port: 
              number: 80
        pathType: Prefix
      - path: /snappyflow
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-apm
            port: 
              number: 8000
        pathType: Prefix
      - path: /user
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-apm
            port: 
              number: 8000
        pathType: Prefix
      - path: /login/
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-apm
            port: 
              number: 8000
        pathType: Prefix
      - path: /sso
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-apm
            port: 
              number: 8000
        pathType: Prefix
      - path: /vizbuilder
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-vizbuilder
            port: 
              number: 8000
        pathType: Prefix
      - path: /alert
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-vizbuilder
            port: 
              number: 8000
        pathType: Prefix
      - path: /deployments
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-vizbuilder
            port: 
              number: 8000
        pathType: Prefix
      - path: /logoperation
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-vizbuilder
            port: 
              number: 8000
        pathType: Prefix
      - path: /cserver
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-commands
            port: 
              number: 8000
        pathType: Prefix
      - path: /es-manager
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-esmanager
            port: 
              number: 8000
        pathType: Prefix
{{- end }}
