{{- if .Values.sfapm.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sfapm.fullname" . }}-trace
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: snappyflow-apm
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /sftrace(/|$)(.*)
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-sftrace
            port:
              number: 8200
        pathType: Prefix
{{- end }}