{{- if .Values.sfapm.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sfapm.fullname" . }}-jaeger
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: snappyflow-apm
    nginx.ingress.kubernetes.io/rewrite-target: /api/traces/
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /jaegertrace
        backend:
          service:
            name: {{ include "sfapm.fullname" . }}-jaegersftrace
            port: 
              number: 14268
        pathType: Prefix
{{- end }}