apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfnginx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sfnginx.name" . }}
    helm.sh/chart: {{ include "sfnginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    snappyflow/component: snappyflow-apm
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sfnginx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sfnginx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: metrics
          image: nginx/nginx-prometheus-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCRAPE_URI
              value: http://127.0.0.1:80/status
            - name: NGINX_RETRIES
              value: "5"
            - name: NGINX_RETRY_INTERVAL
              value: "10s"
          ports:
            - name: nginx-exporter
              containerPort: 9113
          livenessProbe:
            httpGet:
              path: /metric
              port: nginx-exporter
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /metric
              port: nginx-exporter
            initialDelaySeconds: 60
            timeoutSeconds: 10
          resources: {{ toYaml .Values.exporter | nindent 12 }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: apmconfig
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: apmconfig
        configMap:
          name: {{ include "sfnginx.fullname" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
