apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfnginx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sfnginx.name" . }}
    helm.sh/chart: {{ include "sfnginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    snappyflow/component: nginx
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sfnginx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sfnginx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        snappyflow/component: nginx
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.nginx.metrics.port | quote }}
    spec:
      schedulerName: {{ .Values.schedulerName }}
      containers:
      {{- if .Values.sfagent.enabled }}
      - name: sfagent
        image: "{{ .Values.sfagent.image.repository }}:{{ .Values.sfagent.image.tag }}"
        imagePullPolicy: "{{ .Values.sfagent.image.pullPolicy }}"
        command:
          - /app/sfagent
          - -enable-console-log
        env:
          - name: APP_NAME
            value: "{{ .Values.global.sfappname }}"
          - name: PROJECT_NAME
            value: "{{ .Values.global.sfprojectname }}"
        volumeMounts:
        - name: varlog
          mountPath: /var/log/nginx
        - name: sfagent-config
          mountPath: /opt/sfagent/config.yaml
          subPath: config.yaml
        - name: normalization-config
          mountPath: /opt/sfagent/normalization/config.yaml
          subPath: config.yaml
        resources:
{{ toYaml .Values.sfagent.resources | indent 12 }}
       {{- end }}
      - name: logrotate
        image:  "{{ .Values.logrotate.image.repository }}:{{ .Values.logrotate.image.tag }}"
        imagePullPolicy: {{ .Values.logrotate.image.pullPolicy | quote }}
        resources: {{ toYaml .Values.logrotate.resources | nindent 12 }}
        volumeMounts:
          - name: varlog
            mountPath: /var/log/nginx
          - mountPath: /etc/logrotate.conf
            name: logrotate-config
            subPath: logrotate.conf
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 9200
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: http
        readinessProbe:
          httpGet:
            path: /status
            port: http
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: apmconfig
        - name: varlog
          mountPath: /var/log/nginx
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: apmconfig
        configMap:
          name: {{ include "sfnginx.fullname" . }}
      - emptyDir: {}
        name: varlog
      - name: sfagent-config
        configMap:
          name: {{ include "sfnginx.fullname" . }}-sfagent-config
      - name: normalization-config
        configMap:
          name: {{ include "sfnginx.fullname" . }}-normalization-config
      - name: logrotate-config
        configMap:
          name: {{ include "sfnginx.fullname" . }}-logrotate
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
