affinity: {}
archivalKafkaConnectURL: http://sf-datapath-archival-kafka-connect:8083
containerResources:
  ingestcontroller:
    limits:
      cpu: 50m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 10Mi
dataset-controller:
  service:
    servicePort: 5001
db:
  max_idle_connections: 1
  max_open_connections: 3
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/ingest-controller
  tag: 'master-2-0-86'
log-archival:
  service:
    servicePort: 5003
minioEndpoint: sf-datapath-minio:9000
nameOverride: ''
nodeSelector: {}
scehmeRegURL: http://sf-datapath-cp-schema-registry:8081
schedulerName: sf-scheduler
schedules:
  sink: '*/5 * * * *'
serverPort: :5000
service:
  servicePort: 5000
signatureAndKafkaAPIsURL: http://sf-datapath-signatures-and-kafka-apis
spark-manager:
  jobserver:
    service:
      servicePort: 5002
tolerations: []
