apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-logrotate
data:
  logrotate.conf: |
    /var/log/nginx/access-custom.log {
      su root root
      rotate {{ .Values.controller.logrotate.config.rotate_count }}
      {{ .Values.controller.logrotate.config.interval }}
      maxsize {{ .Values.controller.logrotate.config.maxsize }}
      {{ .Values.controller.logrotate.config.mode }}
      missingok
    }
    /var/log/nginx/error-custom.log {
      su root root
      rotate {{ .Values.controller.logrotate.config.rotate_count }}
      {{ .Values.controller.logrotate.config.interval }}
      maxsize {{ .Values.controller.logrotate.config.maxsize }}
      {{ .Values.controller.logrotate.config.mode }}
      missingok
    }