---
enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: ""
podSecurityContext: {}
sfapm:
  image:
    repository: snappyflowml/sfapm-server
    tag: 'python3-4-0-454'
    pullPolicy: IfNotPresent
sfapm_celery_metrics_collector:
  image:
    repository: snappyflowml/sftrace-celery-metrics-collector
    tag: 'python3-4-0-454'
    pullPolicy: IfNotPresent
sfapmaffinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - server
          topologyKey: kubernetes.io/hostname
disable_server_side_cursors: false