apiVersion: v2
name: sf-datapath-and-archival-gateway
description: A Helm chart for Kubernetes
type: application
version: 1.0.6
appVersion: "13.2.21"
dependencies:
- name: nginx
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.21
