affinity: {}
containerResources:
  logarchival:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 10Mi
dataset-controller:
  service:
    servicePort: 5001
fullnameOverride: ''
schedulerName: sf-scheduler
image:
  pullPolicy: Always
  repository: snappyflowml/log-archival
  tag: 'dev-test'
ingest-controller:
  service:
    servicePort: 5000
nameOverride: ''
nodeSelector: {}
serverPort: :5003
service:
  servicePort: 5003
tolerations: []
