apiVersion: v1
entries:
  sf-datapath:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-08-05T13:29:03.077936299Z"
    dependencies:
    - name: nginx-ingress
      repository: file://./sub_charts/nginx-ingress
      version: 3.6.0
    - name: cp-schema-registry
      repository: file://./sub_charts/cp-schema-registry
      version: 0.1.0
    - name: cp-kafka-rest
      repository: file://./sub_charts/cp-kafka-rest
      version: 0.1.0
    - condition: global.archival.enabled
      name: s3-kafka-connect
      repository: file://./sub_charts/s3-kafka-connect
      version: 0.1.0
    - condition: global.archival.enabled
      name: azureblob-kafka-connect
      repository: file://./sub_charts/azureblob-kafka-connect
      version: 0.1.0
    - name: es-kafka-connect
      repository: file://./sub_charts/es-kafka-connect
      version: 0.1.0
    - name: autoscaling
      repository: file://./sub_charts/autoscaling
      version: 0.1.0
    - name: authenticator
      repository: file://./sub_charts/authenticator
      version: 0.1.0
    - name: sfk-interface
      repository: file://./sub_charts/sfk-interface
      version: 0.1.0
    - name: signatures-and-kafka-apis
      repository: file://./sub_charts/signatures-and-kafka-apis
      version: 0.1.0
    description: A Helm chart for Confluent Open Source
    digest: b11c700bf7f4548b1410e464162aed0d3cd51585af7b9f0ebe586c179d56afb3
    name: sf-datapath
    urls:
    - sf-datapath-2.0.9.tgz
    version: 2.0.9
generated: "2021-08-05T13:29:03.057887127Z"
