apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cp-kafka.fullname" . }}-exporter
  labels:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    role: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cp-kafka.fullname" . }}-exporter
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cp-kafka.fullname" . }}-exporter
        release: {{ .Release.Name }}
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
    spec:
      schedulerName: {{ .Values.schedulerName }}
      {{- if .Values.global.sfNodeManager.enabled -}}
      priorityClassName: {{ .Values.global.sfNodeManager.priorityClassName }}
      {{- end }}
      initContainers:
        - name: kafka-ready
          image: "snappyflowml/kafka-zk-check:alpha"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - ./kafka-init.sh
            - {{ .Release.Name }}-cp-kafka-headless:9092
      containers:
      - image: "snappyflowml/kafka-lag-exporter:latest"
        name: kafka-exporter
        args:
          - --kafka.server={{ .Release.Name }}-cp-kafka-headless:9092
          - --web.listen-address=:9308
        ports:
          - containerPort: 9308
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
