# Default values for sf-presto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  sfScheduler: 
    enabled: false
    schedulerName: sf-scheduler
  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: "snappyflow-app"
  snappyflowAppName: "sf-presto"
    
replicaCount: 1

imagePullSecrets: []

image:
  repository: amansingh2708/presto
  pullPolicy: IfNotPresent
  tag: test

# Helm values for sfpresto-worker-prometheus-exporter container
sfprestoWorkerPrometheusExporter:
  image:
    repository: amansingh2708/presto-metric
    tag: test
    pullPolicy: IfNotPresent
  resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi

resourcemanager:
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 4Gi
  # Provide Value same as Pod memory in Mi
  podmem: 4096

coordinator:
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 8Gi
  # Provide Value same as Pod memory in Mi
  podmem: 8192

worker:
  replicaCount: 1
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  # Provide Value same as Pod memory in Mi
  podmem: 4096

aws:
  enabled: false

azure:
  enabled: false
  account: ""
  accesKey: ""

minio:
  enabled: false
  AWS_ACCESS_KEY_ID: XXXX
  AWS_SECRET_ACCESS_KEY: XXXX
  AWS_DEFAULT_REGION: default
  MINIO_ENDPOINT: XXXX

hive:
  # HiveMetaStore service
  service: "archival-hive-metastore.kafka"
  # HiveMetaStore Service port
  port: "9083"

env:
  # How frequently sfpresto-worker-prometheus-exporter fetch metrics
  Metrics_Interval: 3
  #Presto worker Graceful Shutdown Period
  Grace_Period_Seconds: 1

service:
  port: 8080

podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "2112"
  prometheus.io/scrape: "true"

autoscaling:
  enabled: true
  scaleUpPeriod: 30
  scaleDownPeriod: 60
  worker:
    minReplicas: 1
    maxReplicas: 1
    targetQueuedQueries: 5
    targetRunningDrivers: 50
  coordinator:
    minReplicas: 1
    maxReplicas: 1
    targetAverageUtilization: 80

terminationGracePeriodSeconds: 30

nodeSelector: {}
tolerations: []
affinity: {}
