{{- if .Values.autoscaler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sf-cluster-autoscaler.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ include "sf-cluster-autoscaler.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    snappyflow/component:  sf-cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sf-cluster-autoscaler.name" . }}
      role: sf-cluster-autoscaler
  template:
    metadata:
      labels:
        app: {{ include "sf-cluster-autoscaler.name" . }}
        release: {{ .Release.Name }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
        role: sf-cluster-autoscaler
        snappyflow/component: snappyflow-cluster-autoscaler
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
    spec:
      {{- if .Values.global.sfScheduler.enabled }}
      schedulerName: {{ .Values.global.sfScheduler.schedulerName }}
      {{- end }}
      {{- if .Values.global.sfNodeManager.enabled }}
      priorityClassName: {{ .Values.global.sfNodeManager.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ .Values.autoscaler.serviceAccountName }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: sfcluster-autoscaler
          resources:
            {{- toYaml .Values.autoscaler.resources | nindent 12 }}
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/{{ .Values.eks.clusterName }}
            - --balance-similar-node-groups
            - --skip-nodes-with-system-pods=false
            - --scale-down-unneeded-time={{ .Values.autoscaler.nodeUnneededTime }}
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt #/etc/ssl/certs/ca-bundle.crt for Amazon Linux Worker Nodes
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
{{- end }}