---
enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""
disable_server_side_cursors: false
podSecurityContext: {}
esmanager:
  image:
    repository: snappyflowml/sfapm-esmanager
    tag: '1.0.60'
    pullPolicy: IfNotPresent
