{{ define "pgbouncer.ini.1.0.0" }}
[databases]
{{- range $k, $v := .Values.databases }}
{{ $k }} = host={{ $v.host }} port={{ $v.port }} {{ if $v.dbname }}dbname={{ $v.dbname }}{{end}} {{ if $v.user }}user={{ $v.user }}{{end}} {{ if $v.password }}password={{ $v.password }}{{end}} {{ if hasKey $.Values.connConfig $k }}{{ $val := get $.Values.connConfig $k }}{{ if $val.numOfConnections }}pool_size={{ $val.numOfConnections }} max_db_connections={{ $val.numOfConnections }}{{end}}{{end}}
{{- end }}
[pgbouncer]
listen_addr = 0.0.0.0
listen_port = {{ .Values.service.port }}
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt
{{- $users := (join "," (keys .Values.users | sortAlpha)) }}
admin_users = {{ $users }}
stats_users = {{ $users }},stats
pool_mode = {{ .Values.connConfig.default.poolMode }}
default_pool_size = {{ .Values.connConfig.default.numOfConnections }}
max_db_connections = {{ .Values.connConfig.default.numOfConnections }}
query_wait_timeout = {{ .Values.connConfig.default.queryWaitTimeout }}

# extra config
{{- range $k, $v := .Values.extraConfig }}
{{ $k }} = {{ $v }}
{{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}-config
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |-
{{ include "pgbouncer.ini.1.0.0" . | indent 4 }}