# Copyright 2019 Viasat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

apiVersion: v1
# Open Distro for Elasticsearch version
appVersion: 1.13.2
description: 'Open Distro for Elasticsearch'
engine: gotpl
name: elasticsearch-aws
sources:
- hhttps://github.com/opendistro-for-elasticsearch/opendistro-build
# Chart version
version: 1.13.3