affinity: {}
cleanIntervalInHour: 1
cleanup:
  pullPolicy: IfNotPresent
  repository: snappyflowml/query-cleanup
  tag: '11'
containerResources:
  querycleanup:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 10Mi
  querycontroller:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 512Mi
  queryexecutioncontroller:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 512Mi
dataset-controller:
  service:
    servicePort: 5001
executionControler:
  pullPolicy: IfNotPresent
  repository: snappyflowml/query-execution-controller
  tag: '21'
external:
  enabled: false
  externalTrafficPolicy: Cluster
  type: NodePort
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: snappyflowml/query-controller
  tag: 'dev-test'
ingest-controller:
  service:
    servicePort: 5000
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
kafka:
  schemaRegistry:
    host: 10.10.10.10
    port: 8081
log-archival:
  service:
    servicePort: 5003
maxGBToProcessDuringSplitQuery: 1
monitorInterval: 1
nameOverride: ''
nodeSelector: {}
presto:
  catalog: hive
  schema: default
  user: maplelabs
serverPort: :5004
service:
  servicePort: 5004
spark-manager:
  jobserver:
    service:
      servicePort: 5002
tolerations: []
