apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sf-presto.fullname" . }}-resource-manager
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: resource-manager
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.resourcemanager.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: resource-manager
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: resource-manager
        app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
    spec:
      {{- if .Values.global.sfScheduler.enabled }}
      schedulerName: {{ .Values.global.sfScheduler.schedulerName }}
      {{- end }}
      containers:
        - name: sfpresto-coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          command: ["/bin/bash", "-c"]
          args: ["./coordinator-init.sh;"]
          resources:
            {{- toYaml .Values.resourcemanager.resources | nindent 12 }}
          volumeMounts:
          - name: hive-properties
            mountPath: /home/presto-server-0.282/etc/catalog
          - name: config
            mountPath: /home/presto-server-0.282/etc
      volumes:
      - name: hive-properties
        configMap:
          name: {{ include "sf-presto.fullname" . }}-catalog
      - name: config
        configMap:
          name: {{ include "sf-presto.fullname" . }}-resource-manager
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
