apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sf-presto.fullname" . }}-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sf-presto.fullname" . }}-worker
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleDownPeriod }}
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleUpPeriod }}
        value: 1
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: presto_running_drivers
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.targetRunningDrivers }}
  - type: Pods
    pods:
      metric:
        name: presto_queued_queries
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.targetQueuedQueries }}
