apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sinks-monitor
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sfk-interface.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.sink | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "sfk-interface.fullname" . }}; do echo waiting for {{ include "sfk-interface.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "sfk-interface.fullname" . }}/monitor
          restartPolicy: Never
