admin:
  password: admin
  profileKey: admin
  userName: admin
affinity: {}
containerResources:
  authenticator:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 50Mi
db:
  max_idle_connections: 1
  max_open_connections: 2
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/authenticator
  tag: '8'
nameOverride: ''
nodeSelector: {}
serverPort: :5006
service:
  servicePort: 5006
signingKey: mysecretkey
tolerations: []
