{{- if and ( .Values.serviceAccount.create ) ( .Values.global.secrets.minio.enable ) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orc-event-retry-job.serviceAccountName" . }}
  labels:
    {{- include "orc-event-retry-job.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
