global:
  sfScheduler:
    enabled: false
    schedulerName: sf-scheduler

rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if create is true, REQUIRED if create is false
  serviceAccountName: default

imageCredentials:
  registry: https://index.docker.io/v1/
  username: snappyflowml
  token: ""
  email: supervisor@snappyflow.io

config:
  project_name: kubernetes
  app_name: kube-cluster
  # Unique cluster name to add in documents as _tag_cloudName.
  # This is used to create account in APM, this need not be same as actual Kubernets cluster name.
  # Allowed max 32 char, Alphanumeric(a-zA-Z0-9) with dash(-) and underscore(_).
  # REQUIRED field with non empty value
  # project name label key, value of the label will be added in documents as _tag_projectName
  projectname_label: snappyflow/projectname
  #
  # application name label key, value of the label will be added in documents as _tag_appName
  appname_label: snappyflow/appname
  #
  # SnappyFlow APM Elasticsearch Target key copied from APM cloudprofile
  # REQUIRED field with non empty value.
  key: ""

  # set the flag to true for supporting existing customer until their appliance mode apm-server ported to support index with `$` suffixed
  # Will be effective only in case of direct elastic target
  # Not enabling the flag or setting the flag to false will assume apm-server have the latest changes
  # 
  # es_target_index_without_suffix: false

  # SnappyFlow Key for cloud heartbeat and metrics, 
  # If not provided then key used
  # cloud_key: "cluster_key"
  
  # Heartbeat interval
  interval: 300

  # Enable/Disable both cluster metrics and cluster log collection
  cluster_monitoring: true

  # AppView flag to control the data being sent to application project
  app_view: true

  # Individual Cluster documents to collect
  node_static: true
  node_compute: true
  node_volume: true
  pod_static: true
  pod_compute: true
  pod_network: true    # Metrics for pod network interfaces
  pod_volume: true     # Metrics for pod volumes
  container_static: true
  container_dynamic: true
  resource: true
  event-stats: true
  service_static: true
  node_storage: true
  storage-stats: true
  node_network: true   # Metrics for node network interfaces
  # Applicable if node_network is true, enable/disable metrics for physical and virtual interfaces
  node_network_physical_interface: true   # Metrics for node network physical interfaces
  node_network_virtual_interface: false   # Metrics for node network virtual interfaces
  # control plane components to monitor
  apiserver: true
  coredns: true
  kube-proxy: true
  kubelet: true
  controller-manager: true
  kube-scheduler: true
  

# Node Agent
# Per node Plugin Pod
#  container for prometheus poller
#  container for node/pod kubelet monitoring + storage metrics
#  container for fluent-bit logs
node_agent:
  image:
    repository: snappyflowml/kube-node
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  kubelet_configmap:
    interval: 30
  prometheus_configmap:
    log_dir: /tmp
    interval: 30
    system_interval: 60
  plugin_interval:
    elasticsearch:
      cluster: 300
      node: 300
      index: 900
    nginx:
      default: 300
    mysql:
      default: 300
    kafka:
      default: 300
    jmx:
      default: 300
    kafka-jmx:
      default: 300
    kafka-rest:
      default: 300
    kafka-connect:
      default: 300
    zookeeper-zmx:
      default: 300
  drop_cluster_logs: false
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists

  #
  # Features Supported with basic_parsing flag enabled
  # => SingleLine Parsing with snappyflow supported parser plugins
  # => No UI based labelling feature
  # => GeoIP and UaParser Plugin Disabled

  basic_parsing: "Off"

  #
  # Flag name: kubelet-for-metadata
  # Default Value: Off

  # If enabled, in fluentbit, instead of using apiserver, kubelet will be used to enrich the metadata of incoming logs

  # ApiServer rate-limiting is main motive of this feature,
  # However, it will be set to Off in helm, since we would like to be confident on kubelet's metadata info validity or any related issues in various k8s deployment

  kubelet_for_metadata: "Off"

  nodeSelector: {}

forwardmetric:
    # forward metric
    name: sfagentmetric
    enabled: false
    image:
      repository: snappyflowml/sfkube-forward-metric
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8000
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 500Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80

# cluster level plugin Pod
#   Container with cloud heartbeat + cluster document
#   Container for kube events
#   Container for application inventory
cluster_agent:
  image:
    repository: snappyflowml/kube-cluster
    tag: latest
    pullPolicy: Always
  # if enabled
  configmap:
    interval: 300
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

  tolerations: []

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}


