affinity: {}
billing-service:
  enabled: false
  scheme: https
  url: 127.0.0.1:8000/api/v1/records/
bucketPartitonAnalyzeIntervalInMin: 5
bucketPartitonsToAnalyzeInParallelMax: 5
containerResources:
  datasetcontroller:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi
db:
  max_idle_connections: 1
  max_open_connections: 2
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/dataset-controller
  tag: 'master-2-0-86'
ingest-controller:
  service:
    servicePort: 5000
maxPartitionsToAnalyzeConcurrently: 5
nameOverride: ''
nodeSelector: {}
presto:
  catalog: hive
  schema: default
  user: ubuntu
rawDataCleanupDays: 2
schedules:
  billing: 0 * * * *
  detect: '*/30 * * * *'
  expired: 1 0 * * *
  hourly: 0 * * * *
  raw_version_compacted: 5 2 * * *
  refresh_size: 5 1 * * *
serverPort: :5001
service:
  servicePort: 5001
tolerations: []
