admin:
  password: admin
  profileKey: admin
  userName: admin
affinity: {}
containerResources:
  authenticator:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 50Mi
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/authenticator
  tag: '7'
nameOverride: ''
nodeSelector: {}
schedulerName: sf-scheduler
serverPort: :5006
service:
  servicePort: 5006
signingKey: mysecretkey
tolerations: []
