---
enableDebug: false
nameOverride: ""
fullnameOverride: ""
nameOverride: sfapm-python3
fullnameOverride: apm-sfapm-python3
disable_server_side_cursors: false

vizbuilder:
  image:
    repository: snappyflowml/sfapm-vizbuilder
    tag: '4.0.219-python3'
    pullPolicy: IfNotPresent

vizbuilder_celery:
  alert:
    celeryAlertPrometheusExporter:
      image:
        repository: snappyflowml/celery-alert-prometheus-exporter
        tag: 'latest'
        pullPolicy: Always
