apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "signatures-and-kafka-apis.fullname" . }}
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: apm-saas-datapath
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-usercreds
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - ok'
    nginx.ingress.kubernetes.io/auth-secret-type: "auth-file"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /signatures
        backend:
          serviceName: {{ template "signatures-and-kafka-apis.fullname" . }} 
          servicePort: 80
      - path: /kafka-info
        backend:
          serviceName: {{ template "signatures-and-kafka-apis.fullname" . }} 
          servicePort: 80